name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: gcp-cloudrun-nodejs-mysql-app  # Set your GCP project ID
      GCP_REGION: us-central1  # Set your preferred GCP region
      IMAGE_NAME: nodejsapp  # Set your Docker image name
      IMAGE_VERSION: 1.0.${{ github.run_id }}  # Set version format

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"  # Use GCP service account JSON key

      # Step 3: Configure Docker for GCR
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} \
                       -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
                       -f ./gcp_nodejs_app/Dockerfile ./gcp_nodejs_app

      # Step 5: Push Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
